print("\n")
print("****************************************************")
print("|--------------------- PyPong ---------------------|")
print("|                                                  |")
print("|  By WMouton | l33th                              |")
print("|  Profession: Web Development & Linux Security    |")
print("|  Interests: Blockchain, Cryptocurrency,          |")
print("|             Artificial Intelligence, Hacking     |")
print("|  Email : l33th@protonmail.ch                     |")
print("|  Github: github.com/l33th                        |")
print("|                                                  |")    
print("****************************************************")